"use client";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";

export default function DownloadSummaryButton({
  title,
  summaryText,
  file_name,
  createdAt,
}: {
  title: string;
  summaryText: string;
  file_name: string;
  createdAt: string;
}) {
  const handleDownload = () => {
    const summaryContent = `# ${title} 
Generate Summary
Generated on: ${new Date(createdAt).toLocaleDateString()}
${summaryText}
Original File: ${file_name}
Generated by BlinkNote
`;
        const blob = new Blob([summaryContent],{type:'text/plain'});
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `Summary-${title.replace(/[^a-z0-9]/gi, '-')}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
  };
  return (
    <Button
      className="text-purple-600 bg-purple-100 hover:text-purple-700 hover:bg-purple-50 group hover:no-underline h-8 px-3 "
      size="sm"
      onClick={handleDownload}
    >
      <Download className="h-4 w-4 mr-1" />
      Download Summary
    </Button>
  );
}
